version: '3.7'

services:
  app:
    build: ./bm-encomendas
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./bm-encomendas:/usr/app

  api:
    build: ./bm-encomendas_Backend
    command: npm run server
    ports:
      - 4001:4001
    volumes:
      - ./bm-encomendas_Backend:/usr/app
